apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-db-backup-mongo
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          containers:
            - name: mongo-backup
              image: mongo:6.0
              env:
                - name: MONGODB_URI
                  value: "mongodb://rambo:sekret@todo-backend-svc:27017/"
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  BACKUP_FILE="/shared/mongo-backup-$(date +%Y-%m-%d-%H%M%S).gz"
                  echo "Starting MongoDB dump..."
                  mongodump --uri="${MONGODB_URI}" --archive --gzip --file="${BACKUP_FILE}"
                  echo "Backup created successfully: ${BACKUP_FILE}"
              volumeMounts:
                - name: backup-volume
                  mountPath: /shared

            - name: gcloud-upload
              image: google/cloud-sdk:latest
              env:
                - name: GCS_BUCKET_NAME
                  value: "pramod-mongo-backups"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/gcs-credentials.json
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e
                  echo "Activating service account..."
                  gcloud auth activate-service-account --key-file=/secrets/gcs-credentials.json

                  echo "Waiting for backup file to appear..."
                  while [ -z "$(ls -A /shared/mongo-backup-*.gz 2>/dev/null)" ]; do
                    sleep 5
                  done

                  LATEST_BACKUP=$(ls -t /shared/mongo-backup-*.gz | head -n 1)
                  echo "Found backup file: $LATEST_BACKUP"
                  echo "Uploading to bucket gs://${GCS_BUCKET_NAME}..."
                  gsutil cp "$LATEST_BACKUP" gs://${GCS_BUCKET_NAME}/
                  echo "Upload complete."
              volumeMounts:
                - name: backup-volume
                  mountPath: /shared
                - name: gcs-credentials-volume
                  mountPath: /secrets
                  readOnly: true

          volumes:
            - name: backup-volume
              emptyDir: {}
            - name: gcs-credentials-volume
              secret:
                secretName: gcs-credentials
                items:
                  - key: gcs-credentials.json
                    path: gcs-credentials.json

          restartPolicy: OnFailure
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: mongodb-backup-cronjob
# spec:
#   schedule: "0 0 * * *"
#   jobTemplate:
#     spec:
#       # Allow more time for the job to complete, as it installs packages
#       activeDeadlineSeconds: 600
#       backoffLimit: 4
#       template:
#         spec:
#           containers:
#             - name: mongodb-backup
#               image: google/cloud-sdk:latest
#               command:
#                 - "/bin/sh"
#                 - "-c"
#                 - |
#                   # Exit immediately if a command exits with a non-zero status.
#                   set -e
#
#                   echo "--- Step 1: Installing prerequisites (curl, gnupg) ---"
#                   apt-get update
#                   apt-get install -y curl gnupg
#
#                   echo "--- Step 2: Adding official MongoDB repository ---"
#                   # Import the MongoDB public GPG key
#                   curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
#                      gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor
#
#                   echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/debian bookworm/mongodb-org/6.0 main" | \
#                      tee /etc/apt/sources.list.d/mongodb-org-6.0.list
#
#                   echo "--- Step 3: Installing mongodb-database-tools ---"
#                   apt-get update
#                   apt-get install -y mongodb-database-tools
#
#                   echo "--- Step 4: Activating GCS service account ---"
#                   gcloud auth activate-service-account --key-file=/etc/gcs/gcs-credentials.json
#
#                   echo "--- Step 5: Starting MongoDB backup to gs://[YOUR_GCS_BUCKET_NAME] ---"
#                   mongodump --uri="${MONGODB_URI}" --archive --gzip | \
#                   gsutil cp - gs://pramod-mongo-backups/mongodb-backup-$(date +%Y-%m-%dT%H-%M-%S).gz
#
#                   echo "--- Backup complete ---"
#               env:
#                 - name: MONGODB_URI
#                   value: "mongodb://rambo:sekret@todo-backend-svc:27017/"
#               volumeMounts:
#                 - name: gcs-credentials-volume
#                   mountPath: /etc/gcs
#                   readOnly: true
#           restartPolicy: OnFailure
#           volumes:
#             - name: gcs-credentials-volume
#               secret:
#                 secretName: gcs-credentials
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: mongodb-backup-cronjob
# spec:
#   schedule: "0 0 * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: mongodb-backup
#               image: google/cloud-sdk:latest
#               command:
#                 - "/bin/sh"
#                 - "-c"
#                 - |
#                   echo "Installing mongodb-database-tools..."
#                   apt-get update && apt-get install -y mongodb-database-tools
#
#                   echo "Activating GCS service account..."
#                   gcloud auth activate-service-account --key-file=/etc/gcs/gcs-credentials.json
#
#                   echo "Starting MongoDB backup..."
#                   mongodump --uri="${MONGODB_URI}" --archive --gzip | \
#                   gsutil cp - gs://pramod-mongo-backups/mongodb-backup-$(date +%Y-%m-%dT%H-%M-%S).gz
#
#                   echo "Backup complete."
#               env:
#                 - name: MONGODB_URI
#                   value: "mongodb://rambo:sekret@todo-backend-svc:27017/"
#               volumeMounts:
#                 - name: gcs-credentials-volume
#                   mountPath: /etc/gcs
#                   readOnly: true
#           restartPolicy: OnFailure
#           volumes:
#             - name: gcs-credentials-volume
#               secret:
#                 secretName: gcs-credentials
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: mongodb-backup-gcs
#   namespace: project
# spec:
#   schedule: "0 0 * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#             - name: mongo-backup
#               image: buddy00/mongo-backup:1.0
#               env:
#                 - name: MONGO_URI
#                   value: "mongodb://rambo:sekret@todo-backend-svc:27017/"
#                 - name: BUCKET_NAME
#                   value: "pramod-mongo-backups"
#               volumeMounts:
#                 - name: gcp-credentials
#                   mountPath: /secrets
#                   readOnly: true
#               command: ["/bin/sh", "-c"]
#               args:
#                 - |
#                   export GOOGLE_APPLICATION_CREDENTIALS="/secrets/gcp-key.json"
#                   BACKUP_FILE="/backup/mongo-$(date +%F).gz"
#
#                   echo "Running mongodump..."
#                   mongodump --uri="$MONGO_URI" --archive=$BACKUP_FILE --gzip
#
#                   echo "Uploading backup to GCS..."
#                   gsutil cp $BACKUP_FILE gs://$BUCKET_NAME/
#
#                   echo "Backup complete!"
#           restartPolicy: OnFailure
#           volumes:
#             - name: gcp-credentials
#               secret:
#                 secretName: gcp-credentials
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-backup-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
