apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup-gcs
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongo-backup
              image: google/cloud-sdk:latest
              env:
                - name: MONGO_URI
                  value: "mongodb://rambo:sekret@todo-backend-svc:27017/"
                - name: BUCKET_NAME
                  value: "pramod-mongo-backups"
              volumeMounts:
                - name: gcp-credentials
                  mountPath: /secrets
                  readOnly: true
              command:
                - /bin/sh
                - -c
                - |
                  export GOOGLE_APPLICATION_CREDENTIALS="/secrets/gcp-key.json"

                  BACKUP_FILE="/tmp/mongo-$(date +%F).gz"

                  echo "Running mongodump..."
                  mongodump --uri="$MONGO_URI" --archive=$BACKUP_FILE --gzip

                  echo "Uploading backup to GCS..."
                  gsutil cp $BACKUP_FILE gs://$BUCKET_NAME/

                  echo "Backup complete!"
          restartPolicy: OnFailure
          volumes:
            - name: gcp-credentials
              secret:
                secretName: gcp-credentials
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
