apiVersion: v1
kind: Secret
metadata:
  # namespace: project
  name: mongo-secret
data:
  MONGO_INITDB_ROOT_USERNAME: cmFtYm8=
  MONGO_INITDB_ROOT_PASSWORD: c2VrcmV0
  MONGODB_URI: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy8=
