apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  MONGO_INITDB_ROOT_USERNAME: cmFtYm8=
  MONGO_INITDB_ROOT_PASSWORD: c2VrcmV0
  MONGODB_URI: bW9uZ29kYjovL3JhbWJvOnNla3JldEBsb2NhbGhvc3Q6MjcwMTcv
