apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
spec:
  selector:
    app: todo-backend
  clusterIP: None
  ports:
    - port: 3001
      name: todo-backend
    - port: 27017
      name: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-backend
spec:
  serviceName: "todo-backend-svc"
  selector:
    matchLabels:
      app: todo-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          envFrom:
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - mountPath: /data/db
              subPath: mongo
              name: mongo-data-storage
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: todo-backend
          image: PROJECT/IMAGE
          ports:
            - containerPort: 3001
              name: todo-backend
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_URI
          envFrom:
            - configMapRef:
                name: todo-backend-config
          startupProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: mongo-data-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
